### PR TITLE
Remove default URLs from exported JSON data

### PR DESCRIPTION
**Pull request by dtbaker**
## Context:

This is a follow on from https://github.com/rupok/essential-addons-for-elementor-lite/issues/468

This solves the default URL issue in Filterable Gallery, you'll have to implement the same `on_export` modification in any other widgets that define default values.

Once these defaults are removed from the JSON then Envato will be able to support your plugin in the upcoming Template Kit library. 

## Screenshot:

This shows a before and after of the exported JSON data. Notice the default urls are removed.

image

## Todo:

- [ ] Confirm the template still imports as expected with any default URL values removed.
- [ ] Implement the same `on_export` for any other Widgets that set default URLs (e.g. [this one](https://github.com/rupok/essential-addons-for-elementor-lite/blob/394b5e4d41729437feb0cf03fb93409866cb2950/includes/Elements/Image_Accordion.php#L68-L72) )
- [ ] (optional) Try to create a Template Kit with the "[Export](https://wordpress.org/plugins/template-kit-export/)" plugin and confirm Essential Addons works as expected.

### CODE REVIEW

**Comment by sabuz** [comment]
@dtbaker I appreciate your contributions. Can you please create pull request on sabuz-dev branch since we do use master branch for release purpose only.

**Comment by dtbaker** [comment]
This one should now be based off that branch @sabuz 

Unfortunately I have no time to apply or test the same fix for other parts of the plugin export process. 

We have authors wishing to include your plugin on ThemeForest Template Kits and are unable to do so, please let me know when it's possible and I can let the authors know when they can upgrade your plugin.

Thanks!
dtbaker

**Comment by vladanost** [comment]
@sabuz 
Hi,
We are trying to use your plugin as part of an Elementor template kit we are creating for Theme Forest but we are blocked by this url issue.
Can you please address this soon.
Thanks.

**Comment by munkhbayaryo** [comment]
Hi @sabuz ,

I've faced this problem also. 
Can you please fix this issue?

Thanks

**Comment by Fabianfer** [comment]
Hola disculpa me podrias apoyar en una contribucuon para una aplicacion
#428
@dtbaker

**Pull request closed without merging**
